sudo: required

services:
  - docker

before_install:
  - docker build -t dockeryoutube .

script:
  - docker run -e CI=true dockeryoutube npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: "ap-south-1"
  app: "docker-youtube"
  env: "Dockeryoutube-env"
  bucket_name: "elasticbeanstalk-ap-south-1-189487406611"
  bucket_path: "app-docker-youtube"
  skip_cleanup: true

  on:
    branch: main